name: SubIntel CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_backend:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_DB: subIntelDB
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    defaults:
      run:
        working-directory: ./backend/subIntel
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: backend/subIntel/pom.xml

      - name: Run Backend Tests (JUnit & Mockito)
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/subIntelDB
          SPRING_DATASOURCE_USERNAME: postgres
          SPRING_DATASOURCE_PASSWORD: password
          
          JWT_SECRET_KEY: test_jwt_secret_key_must_be_long_enough_for_hs256
          PLAID_CLIENT_ID: test_plaid_client_id
          PLAID_SECRET_SANDBOX: test_plaid_secret
          PLAID_ENV: sandbox
          FRONTEND_URL=http://localhost:3000
        run: mvn test

      - name: Build Backend JAR
        run: mvn clean package -DskipTests

      - name: Upload JAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-jar
          path: backend/subIntel/target/*.jar

  build_frontend:
    runs-on: ubuntu-latest
    needs: build_backend
    defaults:
      run:
        working-directory: frontend/subIntel 
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/subIntel/package-lock.json 

      - name: Install Frontend Dependencies
        run: npm ci

      - name: Run Frontend Tests (Vitest)
        run: npm test 

      - name: Build Frontend Static Files
        run: npm run build 

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/subIntel/dist